### ISSUE TITLE
/new_pathの調査

### ISSUE THREAD

**Issue by MasanariKuniyoshi** [CODEBASE-Okinawa/1000_hackathon_preflop#3]

**Comment by MasanariKuniyoshi** [comment]
index.html.erbのformタグがうまく動かないので、パスの繋ぎ方を調査

**Comment by MasanariKuniyoshi** [comment]
mainブランチから新たにブランチを切って調査、解決時の結果報告

**Comment by hamburger-minato** [comment]
了解です！

**Comment by MasanariKuniyoshi** [comment]
tasks_controller.rbのindexアクションに[@task = Task.new]が記載すると解決する
これによりnewアクションは必要なくなり、並びにnew.html.erbも必要なくなる
